# Generated by Django 3.2.3 on 2021-10-21 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Karnataka', 'Karnataka'), ('Telangana', 'Telanagana'), ('Tamilnadu', 'Tamilnadu')], max_length=50),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Cancel', 'Cancel'), ('Shipped', 'Shipped'), ('On The Way', 'On The way'), ('Delivered', 'Delivered')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('Samsung', 'Samsung'), ('Realme', 'Realme'), ('OnePlus', 'OnePlus'), ('AmericanTourister', 'AmericanTourister'), ('Xiaomi', 'Xiaomi'), ('Zara', 'Zara'), ('AllenSolly', 'AllenSolly'), ('Puma', 'Puma'), ('DressBerry', 'DressBerry'), ('Apple', 'Apple'), ('IndigoNation', 'IndigoNation'), ('Hp', 'Hp')], max_length=50),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
